### ISSUE TITLE
How to get ether to my accounts?

### ISSUE THREAD

**Issue by xaviermaltas** [alastria/test-environment#11]
Hi,

I've been using the `testnet` project, to create my own Ethereum private network together a Truffle distributed application that I've developed. It's a votation application. 
The votes are done through a WebApp and for being this able I need some ether. 

How can I get ether for my accounts?
 
I have tried to unlock validators accounts, doing a `geth attach` to the `.ipc` file of them but they do not have account. Also I have tried to change the `genesis` block and modify the `alloc` parameter to give some ether to some accounts, but I have no result. 

Does somebody have any idea to solve it?

Thank you.

**Comment by netmanito** [comment]
Hello @xaviermaltas, you don't need to have ether to work with this testnet. As a permissioned network, there's no gas fee when you make transactions.
You should be able to deploy your smartcontracts and interact with them without the need of ether.
Kind Regards.

**Comment by xaviermaltas** [comment]
Hi @netmanito, I know that the deploy and the interaction with the smart contract should be able without any fee. In fact, the deploy do not have fees, but when I try to interact via web app with Metamask, appear a Gas Amount that I have to pay. 

- Here my steps to reproduce the error:
`./bin/start_network.sh clean 2 3`
`geth attach http://127.0.0.1:22001`
`personal.unlockAccount(eth.accounts[0])`
Change directory to the Truffle Project directory and deploy contact: 
`truffle migrate --network general1`
Truffle config Network Part making reference the general1 node:     
```
general1: {
      host: "localhost",
      port: 22001,
      network_id: "*", // Match any network id
      gas: 0xfffff,
      gasPrice: 0x0,
      from: "0x74d4c56d8dcbc10a567341bfac6da0a8f04dc41d"
    }
```

![Screenshot from 2019-07-02 15-09-35](https://user-images.githubusercontent.com/46923947/60515218-72d76380-9cdb-11e9-8429-de705d382e43.png)

As it is able to see, the final cost is 0 ETH.

Then I bring up a web app using: 
`npm start`

Here the web app and Metamask connected to the General1 node:
![Screenshot from 2019-07-02 15-14-33](https://user-images.githubusercontent.com/46923947/60515593-39ebbe80-9cdc-11e9-8a9a-ed4f35a2d63b.png)

![Screenshot from 2019-07-02 15-16-30](https://user-images.githubusercontent.com/46923947/60515672-6f90a780-9cdc-11e9-957c-6b72e4999814.png)

In this image it's able to see that it's required to pay a fee.

I have also tried to set the Gas Price to 0 and do not appear any error, but when I press "Confirm" I get that the transaction failed with this message error: 

`Uncaught (in promise) Error: Error: Error: [ethjs-rpc] rpc error with payload {"id":3206657218464,"jsonrpc":"2.0","params":["0xf88b04808507a96049599423ed61cfd8da3b84ff5d0d31f285b0c07051d87b80a436c8c5ee0000000000000000000000000000000000000000000000000000000000000001850470c01b12a0ee9d0064e2db34f001317104b38cef92478cf8fe854fe5a1c2314b92fc07c25fa00534497947d53bbbf7f43f92a7ca87720a0d43b3a648ebf4673af91e816c59dd"],"method":"eth_sendRawTransaction"} Error: invalid sender
    at Object.InvalidResponse (main.js:110990)
    at main.js:114413
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1)
    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1`

What do I must change to solve it?

Thank you.

**Comment by netmanito** [comment]
Hi @xaviermaltas, If I'm not wrong, this testnet is based on old alastria network (arrakis) that doesn't include EIP-155 compliance. please see issue [366](https://github.com/alastria/alastria-node/issues/366).
I think, in order to use metamask, you should download `genesis.json` from current `testnet2` branch and initialize a test network with this genesis in order to have EIP-155 available.
You'll have to init every node for the new genesis.
```geth --datadir /home/ubuntu/alastria/validator1 init /home/ubuntu/alastria-node/data/genesis.json```
Hope this helps.
Regards

**Comment by xaviermaltas** [comment]
Hello @netmanito , I have tried the things that you proposed one week ago, but I've failed again.
I have changed the `genesis.json` with the following code: 
```
{
  "alloc": {
    "0x58b8527743f89389b754c63489262fdfc9ba9db6": {
      "balance": "1000000000000000000000000000"
    },
    "0x74d4C56d8dcbC10A567341bFac6DA0A8F04DC41d": {
      "balance": "1000000000000000000000000000"
    }
  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "config": {
    "chainId": 83584648538,
    "byzantiumBlock": 1,
    "homesteadBlock": 2,
    "eip150Block": 3,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 4,
    "istanbul": {
      "epoch": 30000,
      "policy": 0
    },
    "isQuorum": true
  },
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f85ad594b87dc349944cc47474775dde627a8a171fc94532b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0",
  "gasLimit": "0x2FEFD800",
  "difficulty": "0x1",
  "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "nonce": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}

```
I have also tried to initialize the new configuration adding a code line at `start_node.sh` and `start_faulty_node.sh` , but I get the following error:   `Fatal: Failed to read genesis file: open /home/xavier/Desktop/test-environment/infrastructure/testnet/data/alastria-node/data/genesis.json: no such file or directory`

This is the code that I have added: 
`geth --datadir "${PWD}"/identities/"$NODE_NAME" init "${PWD}"/data/alastria-node/data/genesis.json`

Here an image to show the context where I have done the changes : 
![Screenshot from 2019-07-10 15-12-18](https://user-images.githubusercontent.com/46923947/60971751-25837380-a325-11e9-99f0-0733dc995a97.png)

Could you help me please?

Thank u. :)

**Comment by netmanito** [comment]
Hi @xaviermaltas, I'm not sure if the staff in `test-environment/infrastructure/testnet` currently works.
I'll tell you how I did it.

From this repo, use [threenodes](https://github.com/alastria/test-environment/tree/master/infrastructure/threenodes) section to deploy your testnet.
Once your threenodes testnet is working, cakeshop is not strictly necessary for this action, you can try to hardfork the genesis.

Update then to constantinople.
Modify your **genesis.json** from `~/alastria-node/data/genesis.json` adding the following line:
Put the block number where you want the hardfork to be done. **ex: 491091**

```
    "constantinopleBlock": 491091,
```

Modify the follwing genesis.json line to 0

```
  "eip158Block": 0,
```

Now genesis.json should be ok.

You can start to fork your nodes.

1. Stop nodes.
2. run `geth --datadir /home/ubuntu/alastria/validator1 init /home/ubuntu/alastria-node/data/genesis.json` for each node you want to migrate. (validators and generals)
3. start node.
4. all nodes must have same geth version.
5. wait until block number fork and test.

The following is what should appear, before and after you do the fork.

### Current genesis

```
> admin.nodeInfo
{
  enode: "enode://3905f943ba5446eba164c07ab5f53a84ce17d74ec4d7591f6ec54b9d7608f57cae7cfdf946616385f59cfb5b910161a1f8520cb6f992bcc0d1ab932601205e91@88.21.205.63:21000",
  id: "3905f943ba5446eba164c07ab5f53a84ce17d74ec4d7591f6ec54b9d7608f57cae7cfdf946616385f59cfb5b910161a1f8520cb6f992bcc0d1ab932601205e91",
  ip: "88.21.205.63",
  listenAddr: "[::]:21000",
  name: "Geth/VALIDADOR/v1.8.12-stable-f64dbb25/linux-amd64/go1.9.5",
  ports: {
    discovery: 21000,
    listener: 21000
  },
  protocols: {
    istanbul: {
      config: {
        byzantiumBlock: 1,
        chainId: null,
        eip150Block: 3,
        eip150Hash: "0x0000000000000000000000000000000000000000000000000000000000000000",
        eip155Block: 0,
        eip158Block: 4,
        homesteadBlock: 2,
        isQuorum: true,
        istanbul: {...}
      },
      difficulty: 489923,
      genesis: "0x77a8c93fdee76dcbe099afcda0ee6b2856a0fbebc30fd6bee45ca1a555dd474c",
      head: "0xd5da3ec3a9707f39a17ccc12d1718321292556b11e14566dfaf3cc894a2ff878",
      network: 9535753591
    }
  }
}
```
### New Genesis

```
ubuntu@testenv:~/alastria$ geth attach validator/geth.ipc
Welcome to the Geth JavaScript console!

instance: Geth/VALIDADOR/v1.8.12-stable-f64dbb25/linux-amd64/go1.9.5
coinbase: 0xb87dc349944cc47474775dde627a8a171fc94532
at block: 490348 (Thu, 23 May 2019 15:48:54 CEST)
 datadir: /home/ubuntu/alastria/validator
 modules: admin:1.0 debug:1.0 eth:1.0 istanbul:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> admin.nodeInfo
{
  enode: "enode://3905f943ba5446eba164c07ab5f53a84ce17d74ec4d7591f6ec54b9d7608f57cae7cfdf946616385f59cfb5b910161a1f8520cb6f992bcc0d1ab932601205e91@88.21.205.63:21000",
  id: "3905f943ba5446eba164c07ab5f53a84ce17d74ec4d7591f6ec54b9d7608f57cae7cfdf946616385f59cfb5b910161a1f8520cb6f992bcc0d1ab932601205e91",
  ip: "88.21.205.63",
  listenAddr: "[::]:21000",
  name: "Geth/VALIDADOR/v1.8.12-stable-f64dbb25/linux-amd64/go1.9.5",
  ports: {
    discovery: 21000,
    listener: 21000
  },
  protocols: {
    istanbul: {
      config: {
        byzantiumBlock: 1,
        chainId: 83584648538,
        constantinopleBlock: 493001,
        eip150Block: 3,
        eip150Hash: "0x0000000000000000000000000000000000000000000000000000000000000000",
        eip155Block: 0,
        eip158Block: 0,
        homesteadBlock: 2,
        isQuorum: true,
        istanbul: {...}
      },
      difficulty: 490351,
      genesis: "0x77a8c93fdee76dcbe099afcda0ee6b2856a0fbebc30fd6bee45ca1a555dd474c",
      head: "0xeb9936008cdffb85c9dc224317f0f3ae729b7eb8236fe301de377ffbab664aa7",
      network: 9535753591
    }
  }
}
```
Hope this helps.
Regards

**Comment by javaguirre** [comment]
Hi! Thank you for the contribution, I'm gonna close this issue due to inactivity, but don't hesitate to open it again in case you want to further. :-)
