### ISSUE TITLE
Ejemplo Threenodes : nodo validador siempre offline 

### ISSUE THREAD

**Issue by PilarHB** [alastria/test-environment#5]
Hola
Estoy intentado probar el ejemplo de **Threenodes** pero el nodo validador siempre aparece como offline y en los logs sale este mensaje de error: 

ERROR[06-12|18:20:48] Cannot start mining without etherbase    err="etherbase must be explicitly specified"
Fatal: Failed to start mining: etherbase missing: etherbase must be explicitly specified

¿Hay algún paso más que sea necesario realizar para levantar el nodo?

**Comment by arochaga** [comment]
Hola Pilar,

El Threenodes está algo desactualizado. Para solucionar este problema te aconsejo borrar el repositorio y volvertelo a clonar (es la solución más fácil). Esto suele estar relacionado con algún archivo corrupto.

En cualquier caso, hemos mejorado el threenodes en una nueva herramienta que te permite desplegar una red con una topología personalizada (y así no forzamos el despliegue de una red con sólo tres nodos). El código para la herramienta está en este link: 
https://github.com/alastria/test-environment/tree/master/infrastructure/testnet

Y en este blog de Medium está explicado paso a paso como ponerlo a funcionar:
https://medium.com/coinmonks/deploy-your-own-local-alastria-quorum-test-network-automatically-9f3edb43b4c6

Si tienes cualquier duda nos comentas.

**Comment by PilarHB** [comment]
Hola

Estoy probando la solución de la testnet para 2 nodos validadores y 3 generales. En el momento de ejecutar el comando:
._/bin/start_network.sh clean 2 3 

Se crea el nodo main y en el  validator 1 sale el siguiente error:
_[*] Starting validator1
Verify if /home/pilar/tfg2/test-environment/infrastructure/testnet/logs/ have new files.
Fatal: Unable to attach to remote geth: dial unix network/main/geth.ipc: connect: connection refused_

Una vez en ese punto para completamente. 
El log que resulta es el siguiente:
[quorum_validator1_20180613102033.log](https://github.com/alastria/test-environment/files/2097298/quorum_validator1_20180613102033.log)


Muchas gracias!

**Comment by arochaga** [comment]
Hola Pilar,

No he sido capaz de replicar el error. Me he creado una máquina completamente nueva y me he clonado el repo de cero. He hecho el `./bin/bootstrap.sh` y una vez instaladas todas las dependencias, lanzo la red satisfactoriamente:
```
user@7d803cd955cc:/projects/test-environment/infrastructure/testnet$ ./bin/stop_network.sh
user@7d803cd955cc:/projects/test-environment/infrastructure/testnet$ ./bin/start_network.sh clean 2 2
[!!] Run this script from the directory test-environment/infrastructure/testnet/
[*] Cleaning previous environments
[!!] Run this script from the directory test-environment/infrastructure/testnet
[*] Preparing to clean the environment
[!!] Run this script from the directory test-environment/infrastructure/testnet/
[*] Spreading permissioned nodes config files
[*] Generating nodes in environment
[*] Starting validator nodes
[!!] Excecute from alastria test-environment/infrastructure/testnet/
[*] Starting main
Verify if /projects/test-environment/infrastructure/testnet/logs/ have new files.
[!!] Excecute from alastria test-environment/infrastructure/testnet/
[*] Starting validator1
Verify if /projects/test-environment/infrastructure/testnet/logs/ have new files.
[*] Starting general1
localhost [127.0.0.1] 9001 (?) : Connection refused
localhost [127.0.0.1] 9001 (?) : Connection refused
localhost [127.0.0.1] 9001 (?) : Connection refused
localhost [127.0.0.1] 9001 (?) : Connection refused
localhost [127.0.0.1] 9001 (?) : Connection refused
localhost [127.0.0.1] 9001 (?) : Connection refused
localhost [127.0.0.1] 9001 (?) : Connection refused
localhost [127.0.0.1] 9001 (?) : Connection refused
localhost [127.0.0.1] 9001 (?) : Connection refused
localhost [127.0.0.1] 9001 (?) open
[*] constellation node at 9001 is now up.
Verify if /projects/test-environment/infrastructure/testnet/logs/ have new files.
Verify if /projects/test-environment/infrastructure/testnet/logs/ have new files.
[!!] Excecute from alastria test-environment/infrastructure/testnet/
[*] Starting general2
localhost [127.0.0.1] 9002 (?) : Connection refused
localhost [127.0.0.1] 9002 (?) : Connection refused
localhost [127.0.0.1] 9002 (?) : Connection refused
localhost [127.0.0.1] 9002 (?) open
[*] constellation node at 9002 is now up.
Verify if /projects/test-environment/infrastructure/testnet/logs/ have new files.

user@7d803cd955cc:/projects/test-environment/infrastructure/testnet$ geth attach network/main/geth.ipc
Welcome to the Geth JavaScript console!

instance: Geth/main/v1.7.2-stable-94e1e31e/linux-amd64/go1.9.5
coinbase: 0xb87dc349944cc47474775dde627a8a171fc94532
at block: 119 (Fri, 15 Jun 2018 06:53:34 UTC)
 datadir: /projects/test-environment/infrastructure/testnet/network/main
 modules: admin:1.0 debug:1.0 eth:1.0 istanbul:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

>
```
Mi recomendación es que trates de lanzar al red en un nuevo entorno (ya sea un Docker o una VM nueva) y nos informes si eres capaz de replicar el error (sé que alguien tuvo este mismo problema, pero clonando el repo de nuevo lo solucionó y yo no he sido capaz de replicarlo).

Gracias,
Alfonso

**Comment by PilarHB** [comment]
Hola Alfonso

He conseguido poner en funcionamiento la red de pruebas sin problema. Estaba utilizando el subsistema de Linux para Windows y uno de los ficheros se había configurado mal. He borrado Ubuntu, he añadido el PATH correcto y a partir de ahí ya he podido configurar bien la red.

Muchas gracias

Pilar

**Comment by arochaga** [comment]
Me alegro Pilar. Cierro el issue entonces. Cualquier cosa adicional me comentas.
Gracias.
