### ISSUE TITLE
Máquina Virtual con credenciales

### ISSUE THREAD

**Issue by xaviermaltas** [alastria/test-environment#6]
Buenas,
He intentado utilizar la máquina virtual preconfigurada para testear una red privada, pero me encontrado que al iniciar el Ubuntu 16.04 requiere credenciales. He buscado en el repo y no he encontrado nada.

¿Me podrías ayudar?

Gracias,
Xavier.

**Comment by netmanito** [comment]
Hola @xaviermaltas, 
Las credenciales de la imagen deberían ser 
user: ubuntu
pwd: alastria

Un saludo.
