### ISSUE TITLE
start_main command not found

### ISSUE THREAD

**Issue by msolefonte** [alastria/test-environment#7]
I cloned the repository and followed the tutorial just to found this problem:
```
root@test:/home/test/Documents/alastria/test-environment/infrastructure/testnet# sudo ./bin/start_network.sh clean 2 3 
[!!] Run this script from the directory test-environment/infrastructure/testnet/
[*] Cleaning previous environments
[!!] Run this script from the directory test-environment/infrastructure/testnet
[*] Preparing to clean the environment
[!!] Run this script from the directory test-environment/infrastructure/testnet/
[*] Spreading permissioned nodes config files
[*] Generating nodes in environment
[*] Starting validator nodes
./bin/start_network.sh: line 49: start_main: command not found
```

What I did:

1. git clone https://github.com/alastria/test-environment.git
2. cd test-environment/infrastructure/testnet/
3. sudo apt-get install wget netcat
4. ./bin/bootstrap.sh
5. ./bin/start_network.sh clean 2 3 

I just looked for the function/script `start_main` and it is nowhere. I tried to comment it but then I get this problem, which I do not know if is related or not:

```
root@test:/home/test/Documents/alastria/test-environment/infrastructure/testnet# sudo ./bin/start_network.sh clean 2 3 
[!!] Run this script from the directory test-environment/infrastructure/testnet/
[*] Cleaning previous environments
[!!] Run this script from the directory test-environment/infrastructure/testnet
[*] Preparing to clean the environment
[!!] Run this script from the directory test-environment/infrastructure/testnet/
[*] Spreading permissioned nodes config files
[*] Generating nodes in environment
[*] Starting validator nodes
[!!] Excecute from alastria test-environment/infrastructure/testnet/
[*] Starting main
Verify if /home/test/Documents/alastria/test-environment/infrastructure/testnet/logs/ have new files.
./bin/start_network.sh: line 35: FAULTY_FLAG: unbound variable
[!!] Excecute from alastria test-environment/infrastructure/testnet/
[*] Starting validator1
Verify if /home/test/Documents/alastria/test-environment/infrastructure/testnet/logs/ have new files.
Fatal: Unable to attach to remote geth: dial unix network/main/geth.ipc: connect: connection refused
```

**Comment by msolefonte** [comment]
I modified `./bin/network_start.sh` to add the line `FAULTY_FLAG=" "` just after  `FAULTY_MODE=" "` to prevent the `./bin/start_network.sh: line 35: FAULTY_FLAG: unbound variable` error, which solves it. However, the problem related with the connection refused is still there:

```
root@test:/home/test/Documents/alastria/test-environment/infrastructure/testnet# ./bin/start_network.sh clean 2 3 
[!!] Run this script from the directory test-environment/infrastructure/testnet/
[*] Cleaning previous environments
[!!] Run this script from the directory test-environment/infrastructure/testnet
[*] Preparing to clean the environment
[!!] Run this script from the directory test-environment/infrastructure/testnet/
[*] Spreading permissioned nodes config files
[*] Generating nodes in environment
[*] Starting validator nodes
[!!] Excecute from alastria test-environment/infrastructure/testnet/
[*] Starting main
Verify if /home/test/Documents/alastria/test-environment/infrastructure/testnet/logs/ have new files.
[!!] Excecute from alastria test-environment/infrastructure/testnet/
[*] Starting validator1
Verify if /home/test/Documents/alastria/test-environment/infrastructure/testnet/logs/ have new files.
```

**Comment by netmanito** [comment]
Hi @msolefonte, I'm not sure if this part of the `test-environment` is working correctly.
You should use the `three_node` environment which currently works, [https://github.com/alastria/test-environment/tree/master/infrastructure/threenodes](https://github.com/alastria/test-environment/tree/master/infrastructure/threenodes). It will deploy 1 validator and 2 regular nodes but you can create more nodes as needed.
Regards

**Comment by msolefonte** [comment]
Thanks for your answer. I can understand that the `testenet` is not working correctly. However, it should be added to the `README.md` files to prevent users from losing their time trying to run a non-functional environment. It also would prevent people from getting a bad vision about the global project.

**Comment by netmanito** [comment]
Hi again @msolefonte, I completly agree with you that the README should be updated and make it easier to other users to use this repo. 
I believe no one except you and I are currently working on it, so feel free to PR and suggest improvements  so we can have a more useful environment.
We can work together if you want and leave it tuned.
Regards

**Comment by msolefonte** [comment]
Thank you for accepting the PR.

I have to say that I just checked this project looking for a Quorum implementation but I am not specially interested in Alastria, so is going to be difficult for me to be an active helper. However, if I find more related problems I do not have any kind of problem about suggesting improvements or sending pull requests.

Regards.

**Comment by netmanito** [comment]
Hi @msolefonte, thanks to you on fixing the issues. 
You're welcome!
Best regards.

**Comment by javaguirre** [comment]
I closed it due to inactivity, thank you for the contribution!
